apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: capstone-cluster
  region: us-east-2
nodeGroups:
  - name: worker-group
    instanceType: t2.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
